<?php

namespace App\Services;

use Illuminate\Support\Str;

class OrderIdGenerator
{
    /**
     * Generate a short unique order id with optional prefix.
     * Format: {prefix}-{timestamp}-{random}
     */
    public static function generate(string $prefix = 'nde'): string
    {
        $ts = (int) time();
        $rand = Str::lower(Str::random(6));
        return $prefix . '-' . $ts . '-' . $rand;
    }

    /**
     * Basic validation for order ids generated by this app.
     */
    public static function isValid(string $orderId): bool
    {
        // allow prefix-timestamp-rand (letters, numbers, dashes, underscores)
        return (bool) preg_match('/^[a-z0-9\-_]+\-\d+\-[a-z0-9]{6}$/i', $orderId);
    }
}
